/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testapplication;

import COM.rsa.jsafe.ar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SpringLayout;
import javax.swing.table.DefaultTableModel;
import org.apache.derby.client.am.ResultSet;
import org.apache.derby.client.am.Statement;

/**
 *
 * @author nikhil
 */
public class adstudent extends javax.swing.JFrame {
   testclass tt = new testclass();

    /**
     * Creates new form adstudent
     */
    public adstudent() {
        initComponents();
        show_student();
    }
    public void check(String bcd) throws SQLException{
      
      
       
           String Query  = "SELECT * FROM ROOT.STUDENTS";
             java.sql.Connection con  = java.sql.DriverManager.getConnection("jdbc:derby://localhost:1527/student","Root","root");
           java.sql.Statement stmt = con.createStatement();
            java.sql.ResultSet rs;
            rs = stmt.executeQuery(Query);
            while(rs.next()){
            
            String col = rs.getString("GROUPS");
           System.out.println("col"+col);
  
  
        
       
        String crr[] = col.split(" ",156);
        for(int i = 0; i<crr.length;i++){
            System.out.println(i);
             System.out.println("bcd111111" + bcd);
            System.out.println("crr[i]"+crr[i]);
            if(bcd.equals(crr[i])){
                System.out.println("bcd" + bcd);
                
               String sr = rs.getString("NAME");
                System.out.println("name"+sr);
               String rollnumber = rs.getString("ROLLNUMBER");
                System.out.println("rollnumber"+rollnumber);
               String org = rs.getString("ORGNAZATION");
                System.out.println("org"+org);
               String query  = "INSERT INTO ROOT.ONEGROUP (NAME,ROLLNUMBER,ORGANIZATION) VALUES (?,?,?)";
               
            PreparedStatement st  = con.prepareStatement(query);
                    st.setString(1,sr);
                    st.setString(2,rollnumber);
                    st.setString(3, org);
                    
              if(st.executeUpdate()>0){
              System.out.println("OKKKKKKKKKKKKKKKKKKKKKKKK");
              }
            
                
            }}}
        
        
    
    
    
    }
     public ArrayList<studentdetails>getstudentList(){
         String groupname = GNAME.getText();
         
    studentdetails STU;
ArrayList<studentdetails> studentList = null;
       studentList =new ArrayList<>();
               String query  = "SELECT* FROM ROOT.ONEGROUP";


    try {
        
        Connection con = con = DriverManager.getConnection("jdbc:derby://localhost:1527/student","Root","root");
         Statement  stmt =(Statement) con.createStatement();
          ResultSet rs;
          
                rs = (ResultSet) stmt.executeQuery(query);
                 
                 while(rs.next()){
                     studentdetails  St= new studentdetails(rs.getString("NAME"),rs.getString("ROLLNUMBER"),rs.getString("ORGANIZATION"),rs.getString("GROUPNAME"));
                     studentList.add(St);
                 }
                
         

    } catch (SQLException ex) {
        Logger.getLogger(Btech.class.getName()).log(Level.SEVERE, null, ex);
    }
     
       
      return studentList; 
}
    
public void show_student(){
ArrayList<studentdetails> list = getstudentList();
     DefaultTableModel model  = (DefaultTableModel)jTable1.getModel();
     Object[] row= new Object[4];
     for(int i = 0; i<list.size();i++){
         row[0] = list.get(i).studentname();
         row[1] = list.get(i).rollnumber();
         row[2] = list.get(i).orgnaization();
          row[3] = list.get(i).groups();
         model.addRow(row);
         
     }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        GNAME = new javax.swing.JLabel();
        gcode3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        gcode1 = new javax.swing.JLabel();
        gcd = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        NAME = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 149, 137));

        jPanel2.setBackground(new java.awt.Color(78, 255, 101));

        jLabel1.setBackground(new java.awt.Color(59, 0, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 246));
        jLabel1.setText("show students");

        GNAME.setBackground(new java.awt.Color(59, 0, 255));
        GNAME.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GNAME.setForeground(new java.awt.Color(51, 0, 246));

        gcode3.setBackground(new java.awt.Color(59, 0, 255));
        gcode3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gcode3.setForeground(new java.awt.Color(51, 0, 246));
        gcode3.setText("GROUP NAME: - ");

        jButton1.setBackground(new java.awt.Color(51, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(gcode3, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(398, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(gcode3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 3, 19));

        gcode1.setBackground(new java.awt.Color(59, 0, 255));
        gcode1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gcode1.setForeground(new java.awt.Color(51, 0, 246));
        gcode1.setText("GROUP CODE");

        gcd.setBackground(new java.awt.Color(59, 0, 255));
        gcd.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        gcd.setForeground(new java.awt.Color(51, 0, 246));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gcode1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gcd, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(gcode1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(gcd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTable1.setBackground(new java.awt.Color(0, 149, 137));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "ROLLNUMBER", "ORGANIZATION", "GROUP"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        NAME.setBackground(new java.awt.Color(59, 0, 255));
        NAME.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        NAME.setForeground(new java.awt.Color(0, 149, 137));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(NAME, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          
    
    try{
         String query  = "DELETE FROM ROOT.ONEGROUP";
        Connection con = con = DriverManager.getConnection("jdbc:derby://localhost:1527/student","Root","root");
          PreparedStatement stmt  = con.prepareStatement(query);
        System.out.println("ok1");
    if(stmt.executeUpdate()==1){
         System.out.println("ok2");
          teacher bt = new teacher();
            bt.setVisible(true);
    
        bt.pack();
        bt.setLocationRelativeTo(null);
        bt.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        dispose();
        
    }
    else{
         JOptionPane.showMessageDialog(this,"DATA NOT DELETED");
    }
    
    }catch(Exception ex){
        ex.printStackTrace();
    }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
         
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adstudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel GNAME;
    public javax.swing.JLabel NAME;
    public javax.swing.JLabel gcd;
    public javax.swing.JLabel gcode1;
    public javax.swing.JLabel gcode3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
